### ISSUE TITLE
unknown tool name

### ISSUE THREAD

**Issue by sc0ttdav3y** [phish108/node-jose-tools#47]
Hi,

Running on MacOS with node v13.8.0 and the latest node-jose-tools, and I get the error "unknown tool name" whenever I run any command. 

### Setup

I installed it as per the docs:

```
npm install -g node-jose-tools
```

### Steps to reproduce

The simplest demonstration is this:

```
jose encrypt
```

it returns:

```
unknown tool name
```

### Expected result

As a globally installed node module, I expect to be able to run `jose` from any working directory.  

### Workaround 

Rather than run the documented `jose` command, it instead can run as follows:

```
cd /usr/local/lib/node_modules/node-jose-tools
node index.js encrypt ...
``` 

### Analysis

Digging into the code, I see that `sanitize.js` looks for the file `.lib/${toolname}.js`. 

I think the use of `.` is the root cause.  I put  `console.log(fs.realpathSync('.'))` into `sanitize.js` to debug what `.` is, and I get the current PWD of my shell, and not the root of the project as it expects.

**Comment by phish108** [comment]
Thank you for reporting this issue. I have a fix almost ready.

**Comment by phish108** [comment]
The fixed has been applied and is now available on npmjs.com
